import { combineRgb } from '@companion-module/base'

export const colorRGB = {
	none: combineRgb(16, 16, 16),
	// thanks to  Baldrian Sector for the extended list of color names
	red: combineRgb(160, 0, 0),
	orange: combineRgb(255, 100, 0),
	green: combineRgb(0, 160, 0),
	blue: combineRgb(0, 0, 160),
	purple: combineRgb(80, 0, 80),
	yellow: combineRgb(200, 200, 0),
	avocado: combineRgb(86, 130, 4),
	bastardamber: combineRgb(255, 200, 180),
	bisque: combineRgb(255, 229, 196),
	celadon: combineRgb(171, 225, 175),
	cerulean: combineRgb(94, 127, 178),
	chartreuse: combineRgb(127, 255, 0),
	coral: combineRgb(255, 126, 79),
	ecru: combineRgb(206, 178, 128),
	edgecombgray: combineRgb(218, 212, 197),
	fuchsia: combineRgb(223, 0, 223),
	fulvous: combineRgb(228, 134, 0),
	glaucous: combineRgb(136, 206, 234),
	grey: combineRgb(140, 140, 140),
	indigo: combineRgb(75, 0, 130),
	lilac: combineRgb(204, 135, 153),
	maize: combineRgb(247, 232, 92),
	mauve: combineRgb(153, 51, 102),
	ochre: combineRgb(205, 118, 34),
	olive: combineRgb(128, 128, 0),
	puce: combineRgb(223, 176, 255),
	rufous: combineRgb(169, 27, 7),
	sage: combineRgb(189, 184, 138),
	scarlet: combineRgb(253, 37, 0),
	seafoamgreen: combineRgb(195, 226, 190),
	skyblue: combineRgb(135, 206, 235),
	taupe: combineRgb(178, 138, 108),
	verdigris: combineRgb(65, 129, 108),
	vermilion: combineRgb(228, 66, 52),
	viridian: combineRgb(195, 226, 190),
	wenge: combineRgb(100, 84, 82),
	zaffre: combineRgb(0, 20, 168),
}

export const colorName = [
	{ label: 'None', id: 'none' },
	{ label: 'Red', id: 'red' },
	{ label: 'Orange', id: 'orange' },
	{ label: 'Green', id: 'green' },
	{ label: 'Blue', id: 'blue' },
	{ label: 'Purple', id: 'purple' },
	{ label: 'Yellow', id: 'yellow' },
	{ label: 'Avocado', id: 'avocado' },
	{ label: 'Bastard Amber', id: 'bastardamber' },
	{ label: 'Bisque', id: 'bisque' },
	{ label: 'Celadon', id: 'celadon' },
	{ label: 'Cerulean', id: 'cerulean' },
	{ label: 'Chartreuse', id: 'chartreuse' },
	{ label: 'Coral', id: 'coral' },
	{ label: 'Ecru', id: 'ecru' },
	{ label: 'Edgecomb Gray', id: 'edgecombgray' },
	{ label: 'Fuchsia', id: 'fuchsia' },
	{ label: 'Fulvous', id: 'fulvous' },
	{ label: 'Glaucous', id: 'glaucous' },
	{ label: 'Grey', id: 'grey' },
	{ label: 'Indigo', id: 'indigo' },
	{ label: 'Lilac', id: 'lilac' },
	{ label: 'Maize', id: 'maize' },
	{ label: 'Mauve', id: 'mauve' },
	{ label: 'Ochre', id: 'ochre' },
	{ label: 'Olive', id: 'olive' },
	{ label: 'Puce', id: 'puce' },
	{ label: 'Rufous', id: 'rufous' },
	{ label: 'Sage', id: 'sage' },
	{ label: 'Scarlet', id: 'scarlet' },
	{ label: 'Seafoam Green', id: 'seafoamgreen' },
	{ label: 'Skyblue', id: 'skyblue' },
	{ label: 'Taupe', id: 'taupe' },
	{ label: 'Verdigris', id: 'verdigris' },
	{ label: 'Vermilion', id: 'vermilion' },
	{ label: 'Viridian', id: 'viridian' },
	{ label: 'Wenge', id: 'wenge' },
	{ label: 'Zaffre', id: 'zaffre' },
]
